apiVersion: v1
kind: Secret
metadata:
  name: modelforge-secret
  namespace: default
type: Opaque
data:
  # echo -n "your-password" | base64
  POSTGRES_PASSWORD: "Mzk1MDU0NjE4OTQyNA=="   
  MODELFORGE_API_KEY: "dmFsaWQtYXBpLWtleS0xMjM="   